name: genomeblocks
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pybigwig
  - cooler
  - graph-tool
  - pyranges
  - tqdm
  - cgranges
  - pip:
      - lightmotif