# Example conda_build_config to control variants; adjust as needed for conda-forge CI.
# Keep minimal for now.

# Python versions that the recipe will be built against on CI if not noarch.
# On conda-forge you normally let CI handle the matrix; this is a placeholder for local builds.

python:
  - 3.8
  - 3.9
  - 3.10

numpy:
  - 1.25
