{% set name = "genome" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://github.com/birkiy/genome/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 85693fbdfb5188e9174d482b42bd0e2c32a45e869b531aba561618e014b4ad31

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cgranges
    - numpy
    - pandas
    - pyranges
    - scipy
    - tqdm

test:
  imports:
    - genome
    - genome.locus
  commands:
    - python -c "import genome; assert 'Gene' in genome.__all__"

about:
  home: https://github.com/birkiy/genome
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Genome utilities for loci and architecture.
  description: |
    `genome`provides fluent building blocks for regulatory genomics.
  dev_url: https://github.com/birkiy/genome

extra:
  recipe-maintainers:
    - birkiy
